apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-Ideaflow-setting
spec:
  forms:
    - group: common
      label: 公共配置
      formSchema:
        - $formkit: attachment
          name: favicon
          label: 网站图标
          value: ""
          help: "设置网站图标，建议使用.ico格式"
          accepts:
            - "image/*"
        - $formkit: repeater
          name: backgroundVideos
          label: 背景视频
          value: []
          max: 5
          min: 0
          help: "设置背景视频，优先于背景图片显示"
          children:
            - $formkit: attachment
              name: url
              id: url
              label: 视频
              accepts:
                - "video/*"
        - $formkit: repeater
          name: backgroundImgs
          label: 背景大图
          value: []
          max: 5
          min: 1
          help: "当没有配置视频时显示背景图片"
          children:
            - $formkit: attachment
              name: url
              id: url
              label: 图片
              accepts:
                - "image/*"
        - $formkit: checkbox
          name: isFullScreen
          label: 头部大图or视频全屏
          value: false
          help: "设置头部大图or视频是否全屏显示"
        - $formkit: checkbox
          name: showStarryEffect
          label: 显示星空效果
          value: true
          help: "设置是否显示星空特效"
        - $formkit: checkbox
          name: showRippleEffect
          label: 显示波浪效果
          value: true
          help: "设置是否显示波浪特效"
    - group: footer
      label: 页脚配置
      formSchema:
        - $formkit: attachment
          name: footerAnimalImage
          label: 页脚动物装饰图
          value: ""
          help: "设置页脚动物装饰图片"
          accepts:
            - "image/*"
        - $formkit: checkbox
          name: showFooterAnimalImageOnMobile
          label: 移动端显示动物装饰图
          value: false
          help: "设置是否在移动端显示页脚动物装饰图片"
        - $formkit: text
          name: footerSlogan
          label: 页脚标语
          value: ""
          help: "设置页脚显示的个性化标语"
        - $formkit: text
          name: contactEmail
          label: 联系邮箱
          value: ""
          help: "设置联系邮箱地址"
        - $formkit: text
          name: contactText
          label: 联系文本
          value: "联系我"
          help: "设置联系链接显示的文本"
        - $formkit: text
          name: supportText
          label: 支持文本
          value: ""
          help: "设置网站支持信息文本"
        - $formkit: url
          name: supportLink
          label: 支持链接
          value: ""
          help: "设置网站支持信息链接"
        - $formkit: text
          name: icp
          label: 备案号
          value: ""
          help: "设置网站备案号"
        - $formkit: url
          name: icpLink
          label: 备案链接
          value: ""
          help: "设置备案信息链接"
        - $formkit: text
          name: ga
          label: 公安备案号
          value: ""
          help: "设置公安备案号"
        - $formkit: url
          name: gaLink
          label: 备案链接
          value: ""
          help: "设置备案信息链接"

    - group: blogger
      label: 博主信息
      formSchema:
        - $formkit: attachment
          name: avatar
          label: 博主头像
          value: ""
          help: "设置博主头像，建议尺寸200x200"
        - $formkit: text
          name: nickname
          label: 博主昵称
          value: ""
          help: "设置博主昵称，默认使用站点标题"
        - $formkit: text
          name: bio
          label: 个人简介
          value: ""
          help: "一句话介绍自己"
        - $formkit: text
          name: location
          label: 所在地
          value: ""
          help: "设置所在地，如：北京"
        - $formkit: repeater
          name: social_links
          label: 社交链接
          id: social_links
          value: []
          children:
            - $formkit: text
              name: platform
              label: 平台
              value: ""
              validation: required
            - $formkit: url
              name: url
              label: 链接
              value: ""
              validation: required
            - $formkit: text
              name: icon
              label: 图标
              value: ""
              help: "使用SVG图标代码"
